on:
  pull_request:
    types: [ closed ]
    branches:
      - master
      - main

name: Continuous delivery of official DASI website
jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '14.15'
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: npm install -g ngh

    - name: build
      run: ng build --prod --base-href https://dasiusp.com/

    - name: deploy
      run: ngh --dir=dist/DASIWeb

